# Generated by Django 6.0 on 2025-12-11 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_payment_user_payment_name'),
        ('programs', '0002_registration_quantity_alter_registration_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='registration_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.registration'),
        ),
    ]
