# Generated by Django 6.0 on 2025-12-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_registration_quantity_alter_registration_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='registration_deadline',
            new_name='reg_deadline',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='program',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='program',
            name='is_reg_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='program',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
