# Generated by Django 6.0 on 2025-12-15 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_rename_registration_deadline_program_reg_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='reg_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
